Users update (backend)
Social-projects-Rivne/Rv-041WebUI-python pull request #40
Opened 2019-02-19 03:42 UTC by IvanAnto

Another pull request into branch users_list.

2019-02-19 12:11 UTC, MaxSukhovetskyi approved these changes

2019-02-20 13:34 UTC, MaxSukhovetskyi requested changes

2019-02-20 13:34 UTC, MaxSukhovetskyi commented on easyrest/routes.py
> +    config.add_route('user_update', 'user/{user_id:\d+}', request_method="PUT")
You can aggregate CRUD logic in one route name (like 'user'), and have request_method=["PUT", "POST", "DELETE"] etc.

2019-02-20 16:55 UTC, IvanAnto commented on easyrest/routes.py
> +    config.add_route('user_update', 'user/{user_id:\d+}', request_method="PUT")
I thought about it. But chose to separate them. With this approach, it is more clear which parameter is expected and which action the request goes to + you can manage the URL more flexiblе (for example: `users/` for users list and `user/` for for a specific user).

2019-02-20 18:53 UTC, MaxSukhovetskyi commented on easyrest/routes.py
> +    config.add_route('user_update', 'user/{user_id:\d+}', request_method="PUT")
Right now you have pull request "Users deletion (backend)" where you create new router name for deletion. Quote:
` config.add_route('user_delete', 'user/{user_id:\d+}', request_method="DELETE")`
Here you have:
`config.add_route('user_update', 'user/{user_id:\d+}', request_method="PUT")`
Both of them can be combined to something like:
`config.add_route('user', 'user/{user_id:\d+}', request_method=["PUT", "DELETE"])`

2019-02-21 13:42 UTC, IvanAnto commented on easyrest/routes.py
> +    config.add_route('user_update', 'user/{user_id:\d+}', request_method="PUT")
What's the difference?

2019-02-22 13:04 UTC, MaxSukhovetskyi approved these changes

2019-02-22 21:45 UTC, RazSKg approved these changes

2019-02-22 22:19 UTC, merged