Docker environment
Social-projects-Rivne/Rv-041WebUI-python pull request #6
Opened 2019-01-01 16:11 UTC by IvanAnto

Added configuration for deployment on Docker. Also added add-on for docker compose 
for simplified management of application services.

2019-01-01 16:15 UTC, RazSKg approved these changes

2019-01-01 22:04 UTC, serge30 requested changes
Please update `README.md` with steps to deploy the project on dev environments using your script and Docker.

2019-01-01 22:04 UTC, serge30 commented on Dockerfile
> +FROM python:2.7.15
`python:2.7` is enough.

2019-01-01 22:04 UTC, serge30 commented on frontend/Dockerfile
> +FROM node:10.15.0
`node:10.15` is enough. Please try do not set hotfix version and use only parts. As there might be new hotfix releases which fixes some vulnerabilities and bugs, and you'd like to pick them.

2019-01-02 09:49 UTC, serge30 approved these changes

2019-01-02 09:49 UTC, IvanAnto commented
- Fixed version of images
- Added deployment instructions through Docker into README.md

Additionally:
- Corrected help in the deployment script
- Made minor changes to the docker-compose.yml and development.ini

2019-01-02 20:54 UTC, merged